# SPDX-FileCopyrightText: 2017-2022 Contributors to the OpenSTEF project <korte.termijn.prognoses@alliander.com> # noqa E501
#
# SPDX-License-Identifier: MPL-2.0

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "openstef_dbc"
    reviewers:
      - "FrankKr"
      - "wfstoel"
      - "JanMaartenVanDoorn"
      - "Davidswinkels"
    target-branch: "main"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # Unfortunately, you don't have more control over PR names...
      separator: "-"
