# SPDX-FileCopyrightText: 2025 Contributors to the OpenSTEF project <short.term.energy.forecasts@alliander.com>
#
# SPDX-License-Identifier: MPL-2.0

[project]
name = "openstef-meta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["openstef-core", "openstef-models"]

[tool.uv.sources]
openstef-models = { workspace = true }
openstef-core = { workspace = true }


[tool.hatch.build.targets.wheel]
packages = ["src/openstef_meta"]
