# SPDX-FileCopyrightText: 2025 Contributors to the OpenSTEF project <short.term.energy.forecasts@alliander.com>
#
# SPDX-License-Identifier: MPL-2.0

[build-system]
build-backend = "hatchling.build"

requires = [ "hatchling" ]

[project]
name = "openstef-beam"
version = "0.0.0"
description = "Backtesting, Evaluation, Analysis and Metrics (BEAM) library for OpenSTEF"
readme = "README.md"
keywords = [ "energy", "forecasting", "machinelearning" ]
license = "MPL-2.0"
authors = [
  { name = "Alliander N.V", email = "short.term.energy.forecasts@alliander.com" },
]
requires-python = ">=3.12,<4.0"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]

dependencies = [
  "openstef-core>=4,<5",
  "plotly>=6.3",
  "pyyaml>=6.0.2",
  "scoringrules>=0.8",
  "tqdm>=4.67.1",
]

optional-dependencies.all = [
  "s3fs>=2025.5.1",
]
urls.Documentation = "https://openstef.github.io/openstef/index.html"
urls.Homepage = "https://lfenergy.org/projects/openstef/"
urls.Issues = "https://github.com/OpenSTEF/openstef/issues"
urls.Repository = "https://github.com/OpenSTEF/openstef"

[tool.hatch.build.targets.wheel]
packages = [ "src/openstef_beam" ]

[tool.uv.sources]
openstef-core = { workspace = true }
